controller_server:
  ros__parameters:
    use_sim_time: false

    # example local_costmap params nested safely
    local_costmap:
      footprint:
        - [-0.24, -0.14]
        - [-0.24, 0.14]
        - [0.10, 0.14]
        - [0.10, -0.14]

    # controller switcher requires a default list
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"