#
# copied from /opt/ros/jazzy/share/nav2_bringup/params/nav2_params.yaml
#
# see https://docs.nav2.org/configuration/index.html
#     https://automaticaddison.com/ros-2-navigation-tuning-guide-nav2/
#     https://github.com/slgrobotics/robots_bringup/blob/main/Docs/ROS-Jazzy/README-BT.md
#

# see https://docs.nav2.org/configuration/packages/configuring-amcl.html
amcl:
  ros__parameters:
    enable_stamped_cmd_vel: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: "base_footprint"
    scan_topic: "scan"
    #odom_topic: "odometry/local"  # for now, using remapping in amcl.launch.py

    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0 # use range reported by the sensor
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 1000 # Reduced to optimize performance
    min_particles: 300 # Reduced to optimize performance
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true # Broadcasting the map->odom transform is why we use ACML.
    transform_tolerance: 0.3  # delay in transform (tf) data that is tolerable in seconds. Default 1.0
    update_min_a: 0.1 # Radians. Default 0.2=11.5 degrees. Less is better for slow or precise movements.
    update_min_d: 0.1 # Meters. Default 0.25. Less is better for slow-moving robots.
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.1 # Default 0.005. Greater value compensates for short readings, such as small obstacles or reflective surfaces
